2024-05-24 18:52:28,384 - INFO - Initializing CubicForwardSpline
2024-05-24 18:52:28,384 - INFO - Finished initializing CubicForwardSpline
2024-05-24 18:52:29,545 - INFO - Starting load_data
2024-05-24 18:52:29,565 - INFO - Finished load_data
2024-05-24 18:52:32,924 - INFO - Starting run_one_time
2024-05-24 18:52:32,925 - INFO - Starting calc_spline
2024-05-24 18:52:32,980 - INFO - Finished calc_spline
2024-05-24 18:52:32,980 - INFO - Finished run_one_time
2024-05-24 18:52:34,464 - INFO - Starting run_linear
2024-05-24 18:52:34,465 - ERROR - Exception occurred in run_linear
Traceback (most recent call last):
  File "/Users/arbili/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py", line 271, in _minimize_slsqp
    ctype = con['type'].lower()
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/arbili/Arik/CubicForwardSpline/notebooks/../model/model.py", line 201, in run_linear
    ret = minimize(fun=self.calc_spline, x0=self.adj_params_flatten,
  File "/Users/arbili/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 719, in minimize
    res = _minimize_slsqp(fun, x0, args, jac, bounds,
  File "/Users/arbili/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/scipy/optimize/_slsqp_py.py", line 275, in _minimize_slsqp
    raise TypeError('Constraints must be defined using a '
TypeError: Constraints must be defined using a dictionary.
